changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Bugs 
      labels:
        - Semver-Minor
        - bug
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    
