stages:
  - prepare
  - release  

prepare_description:
  stage: prepare
  image: golang:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo jiraURL $jiraURL
    - echo jiraUsername $jiraUsername
    - echo jiraPassword $jiraPassword
    - echo gitURL $gitURL
    - echo gitToken $gitToken
    - echo jiraClosedFeatureFilter $jiraClosedFeatureFilter
    - echo issuePattern $issuePattern
    - go install github.com/happyagosmith/jig@latest
    - jig --version
    - jig generate .jig/rn.tpl -m .jig/model.yaml --jiraURL ${jiraURL} --jiraUsername ${jiraUsername} --jiraPassword ${jiraPassword} --gitURL ${gitURL} --gitToken ${gitToken}  --issuePattern ${issuePattern}  --withEnrich -o description.md > jig.log
  artifacts:
    paths:
      - description.md
      - jig.log

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: description.md
  dependencies:
    - prepare_description